"""phase 5 watch: watch_source watch_score

Revision ID: a8a87bee47ea
Revises: dca53ce97a42
Create Date: 2026-07-03 11:46:34.827615

Watch-integration tables (P5-T1, FR-X2/FR-Q5). `watch_source` holds the
configured Tautulli/Plex/Jellyfin servers (credentials Fernet-encrypted);
`watch_score` is the durable score cache (PRD §11) rebuilt on a TTL by the
watch refresh loop. Dialect-portable (NFR-2); the autogenerated GUID-type
churn on the existing tables is a known SQLite-vs-GUID false positive and is
deliberately omitted.
"""

from collections.abc import Sequence

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import advanced_alchemy.types.json
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a8a87bee47ea"
down_revision: str | Sequence[str] | None = "dca53ce97a42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "watch_score",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("media_type", sa.String(length=8), nullable=False),
        sa.Column("title_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("watched_recently", sa.Boolean(), nullable=False),
        sa.Column("watched_frequently", sa.Boolean(), nullable=False),
        sa.Column("watchlisted", sa.Boolean(), nullable=False),
        sa.Column(
            "sources",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_score")),
        sa.UniqueConstraint(
            "media_type", "title_key", "year", name="uq_watch_score_identity"
        ),
    )
    op.create_index(
        op.f("ix_watch_score_media_type"), "watch_score", ["media_type"], unique=False
    )
    op.create_index(
        op.f("ix_watch_score_refreshed_at"),
        "watch_score",
        ["refreshed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watch_score_title_key"), "watch_score", ["title_key"], unique=False
    )

    op.create_table(
        "watch_source",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("credential_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "config",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "health_snapshot",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_source")),
        sa.UniqueConstraint("name", name=op.f("uq_watch_source_name")),
    )
    op.create_index(
        op.f("ix_watch_source_source_type"),
        "watch_source",
        ["source_type"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_watch_source_source_type"), table_name="watch_source")
    op.drop_table("watch_source")
    op.drop_index(op.f("ix_watch_score_title_key"), table_name="watch_score")
    op.drop_index(op.f("ix_watch_score_refreshed_at"), table_name="watch_score")
    op.drop_index(op.f("ix_watch_score_media_type"), table_name="watch_score")
    op.drop_table("watch_score")
