"""phase 1 schema: auth, instances, mirror, doctor

Revision ID: c4ede387c88f
Revises:
Create Date: 2026-07-02 02:46:29.294870

"""

from collections.abc import Sequence

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import advanced_alchemy.types.json
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4ede387c88f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_provider_config",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("provider_type", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_provider_config")),
        sa.UniqueConstraint(
            "provider_type", name=op.f("uq_auth_provider_config_provider_type")
        ),
    )
    op.create_table(
        "doctor_run",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "summary",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_run")),
    )
    op.create_table(
        "lingarr_instance",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("api_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column(
            "health_snapshot",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lingarr_instance")),
        sa.UniqueConstraint("name", name=op.f("uq_lingarr_instance_name")),
    )
    op.create_table(
        "user_account",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("oidc_subject", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name=op.f("uq_user_account_email")),
        sa.UniqueConstraint("oidc_subject", name=op.f("uq_user_account_oidc_subject")),
    )
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_account_username"), ["username"], unique=True
        )

    op.create_table(
        "api_key",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "user_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_api_key_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_key_key_hash")),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_prefix"), ["prefix"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_api_key_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "bazarr_instance",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("api_key_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column(
            "lingarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column(
            "capabilities",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "health_snapshot",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lingarr_instance_id"],
            ["lingarr_instance.id"],
            name=op.f("fk_bazarr_instance_lingarr_instance_id_lingarr_instance"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bazarr_instance")),
        sa.UniqueConstraint("name", name=op.f("uq_bazarr_instance_name")),
    )
    op.create_table(
        "doctor_finding",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "run_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("check_id", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column(
            "lingarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("fix_guidance", sa.Text(), nullable=False),
        sa.Column(
            "data",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_doctor_finding_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lingarr_instance_id"],
            ["lingarr_instance.id"],
            name=op.f("fk_doctor_finding_lingarr_instance_id_lingarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["doctor_run.id"],
            name=op.f("fk_doctor_finding_run_id_doctor_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_finding")),
    )
    with op.batch_alter_table("doctor_finding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctor_finding_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index("ix_doctor_finding_check", ["check_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_doctor_finding_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "movie",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("radarr_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("sort_title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column(
            "audio_language",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "tags",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_movie_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movie")),
        sa.UniqueConstraint(
            "bazarr_instance_id", "radarr_id", name=op.f("uq_movie_bazarr_instance_id")
        ),
    )
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movie_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_movie_instance_sort_title",
            ["bazarr_instance_id", "sort_title"],
            unique=False,
        )

    op.create_table(
        "series",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("sonarr_series_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("sort_title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("ended", sa.Boolean(), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column(
            "audio_language",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "tags",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_series_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "sonarr_series_id",
            name=op.f("uq_series_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_series_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_series_instance_sort_title",
            ["bazarr_instance_id", "sort_title"],
            unique=False,
        )

    op.create_table(
        "sync_run",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "counters",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_sync_run_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run")),
    )
    with op.batch_alter_table("sync_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_run_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_sync_run_instance_created",
            ["bazarr_instance_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "episode",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column(
            "series_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("sonarr_series_id", sa.Integer(), nullable=False),
        sa.Column("sonarr_episode_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column(
            "audio_language",
            sa.JSON()
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
            .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
            .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_episode_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            name=op.f("fk_episode_series_id_series"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episode")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "sonarr_episode_id",
            name=op.f("uq_episode_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_episode_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_episode_instance_series_number",
            ["bazarr_instance_id", "sonarr_series_id", "season", "episode"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_episode_series_id"), ["series_id"], unique=False
        )

    op.create_table(
        "subtitle",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column(
            "episode_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column(
            "movie_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hi", sa.Boolean(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_subtitle_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episode.id"],
            name=op.f("fk_subtitle_episode_id_episode"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
            name=op.f("fk_subtitle_movie_id_movie"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subtitle")),
    )
    with op.batch_alter_table("subtitle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subtitle_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_episode_id"), ["episode_id"], unique=False
        )
        batch_op.create_index(
            "ix_subtitle_instance_language",
            ["bazarr_instance_id", "language"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_movie_id"), ["movie_id"], unique=False
        )

    op.create_table(
        "wanted_subtitle",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column(
            "episode_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column(
            "movie_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hi", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_wanted_subtitle_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episode.id"],
            name=op.f("fk_wanted_subtitle_episode_id_episode"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
            name=op.f("fk_wanted_subtitle_movie_id_movie"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wanted_subtitle")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "episode_id",
            "language",
            "forced",
            "hi",
            name=op.f("uq_wanted_subtitle_bazarr_instance_id_episode_id"),
        ),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "movie_id",
            "language",
            "forced",
            "hi",
            name=op.f("uq_wanted_subtitle_bazarr_instance_id_movie_id"),
        ),
    )
    with op.batch_alter_table("wanted_subtitle", schema=None) as batch_op:
        batch_op.create_index(
            "ix_wanted_instance_language",
            ["bazarr_instance_id", "language"],
            unique=False,
        )
        batch_op.create_index(
            "ix_wanted_instance_last_seen",
            ["bazarr_instance_id", "last_seen_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_wanted_subtitle_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_wanted_subtitle_episode_id"), ["episode_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wanted_subtitle_movie_id"), ["movie_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wanted_subtitle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wanted_subtitle_movie_id"))
        batch_op.drop_index(batch_op.f("ix_wanted_subtitle_episode_id"))
        batch_op.drop_index(batch_op.f("ix_wanted_subtitle_bazarr_instance_id"))
        batch_op.drop_index("ix_wanted_instance_last_seen")
        batch_op.drop_index("ix_wanted_instance_language")

    op.drop_table("wanted_subtitle")
    with op.batch_alter_table("subtitle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_movie_id"))
        batch_op.drop_index("ix_subtitle_instance_language")
        batch_op.drop_index(batch_op.f("ix_subtitle_episode_id"))
        batch_op.drop_index(batch_op.f("ix_subtitle_bazarr_instance_id"))

    op.drop_table("subtitle")
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episode_series_id"))
        batch_op.drop_index("ix_episode_instance_series_number")
        batch_op.drop_index(batch_op.f("ix_episode_bazarr_instance_id"))

    op.drop_table("episode")
    with op.batch_alter_table("sync_run", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_run_instance_created")
        batch_op.drop_index(batch_op.f("ix_sync_run_bazarr_instance_id"))

    op.drop_table("sync_run")
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_index("ix_series_instance_sort_title")
        batch_op.drop_index(batch_op.f("ix_series_bazarr_instance_id"))

    op.drop_table("series")
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.drop_index("ix_movie_instance_sort_title")
        batch_op.drop_index(batch_op.f("ix_movie_bazarr_instance_id"))

    op.drop_table("movie")
    with op.batch_alter_table("doctor_finding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctor_finding_run_id"))
        batch_op.drop_index("ix_doctor_finding_check")
        batch_op.drop_index(batch_op.f("ix_doctor_finding_bazarr_instance_id"))

    op.drop_table("doctor_finding")
    op.drop_table("bazarr_instance")
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_key_prefix"))

    op.drop_table("api_key")
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_account_username"))

    op.drop_table("user_account")
    op.drop_table("lingarr_instance")
    op.drop_table("doctor_run")
    op.drop_table("auth_provider_config")
    # ### end Alembic commands ###
