"""initial schema

Revision ID: c4f733b8b976
Revises:
Create Date: 2026-07-04 13:04:48.326853

"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import advanced_alchemy.types.datetime
import advanced_alchemy.types.guid
import advanced_alchemy.types.json
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4f733b8b976"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _json_column() -> sa.types.TypeEngine[object]:
    return (
        sa.JSON()
        .with_variant(postgresql.JSONB(astext_type=sa.Text()), "cockroachdb")
        .with_variant(advanced_alchemy.types.json.ORA_JSONB(), "oracle")
        .with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")
    )


# Stable seed identities so re-imports and docs can reference them.
OBSERVE_ID = uuid.UUID("019739a0-0000-7000-8000-000000000001")
CONSERVATIVE_ID = uuid.UUID("019739a0-0000-7000-8000-000000000002")
BALANCED_ID = uuid.UUID("019739a0-0000-7000-8000-000000000003")
AGGRESSIVE_ID = uuid.UUID("019739a0-0000-7000-8000-000000000004")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setup_state",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_app_setup_state_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_setup_state")),
    )
    op.create_table(
        "auth_provider_config",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("provider_type", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("settings_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_provider_config")),
        sa.UniqueConstraint(
            "provider_type", name=op.f("uq_auth_provider_config_provider_type")
        ),
    )
    op.create_table(
        "doctor_run",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_run")),
    )
    op.create_table(
        "lingarr_instance",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("api_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column("health_snapshot", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lingarr_instance")),
        sa.UniqueConstraint("name", name=op.f("uq_lingarr_instance_name")),
    )
    op.create_table(
        "notification_route",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("events", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_route")),
        sa.UniqueConstraint("name", name=op.f("uq_notification_route_name")),
    )
    op.create_table(
        "preset",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("built_in", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("values", _json_column(), nullable=True),
        sa.Column("rails", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preset")),
        sa.UniqueConstraint("name", name=op.f("uq_preset_name")),
    )
    with op.batch_alter_table("preset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_preset_active"), ["active"], unique=False)

    _seed_presets()

    op.create_table(
        "translation_profile",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("values", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translation_profile")),
        sa.UniqueConstraint("name", name=op.f("uq_translation_profile_name")),
    )
    op.create_table(
        "user_account",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("oidc_subject", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name=op.f("uq_user_account_email")),
        sa.UniqueConstraint("oidc_subject", name=op.f("uq_user_account_oidc_subject")),
    )
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_account_username"), ["username"], unique=True
        )

    op.create_table(
        "watch_score",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("media_type", sa.String(length=8), nullable=False),
        sa.Column("title_key", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("watched_recently", sa.Boolean(), nullable=False),
        sa.Column("watched_frequently", sa.Boolean(), nullable=False),
        sa.Column("watchlisted", sa.Boolean(), nullable=False),
        sa.Column("sources", _json_column(), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_score")),
        sa.UniqueConstraint(
            "media_type", "title_key", "year", name="uq_watch_score_identity"
        ),
    )
    with op.batch_alter_table("watch_score", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_watch_score_media_type"), ["media_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watch_score_refreshed_at"), ["refreshed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watch_score_title_key"), ["title_key"], unique=False
        )

    op.create_table(
        "watch_source",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("credential_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", _json_column(), nullable=True),
        sa.Column("health_snapshot", _json_column(), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_source")),
        sa.UniqueConstraint("name", name=op.f("uq_watch_source_name")),
    )
    with op.batch_alter_table("watch_source", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_watch_source_source_type"), ["source_type"], unique=False
        )

    op.create_table(
        "api_key",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "user_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_api_key_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_key_key_hash")),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_prefix"), ["prefix"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_api_key_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "bazarr_instance",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("api_key_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column(
            "lingarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column("capabilities", _json_column(), nullable=True),
        sa.Column("health_snapshot", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lingarr_instance_id"],
            ["lingarr_instance.id"],
            name=op.f("fk_bazarr_instance_lingarr_instance_id_lingarr_instance"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bazarr_instance")),
        sa.UniqueConstraint("name", name=op.f("uq_bazarr_instance_name")),
    )
    op.create_table(
        "lingarr_actuals",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "lingarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("sample_files", sa.Integer(), nullable=False),
        sa.Column("lines_per_file", sa.Float(), nullable=False),
        sa.Column("characters_per_file", sa.Float(), nullable=False),
        sa.Column("total_files", sa.Integer(), nullable=False),
        sa.Column("total_lines", sa.Integer(), nullable=False),
        sa.Column("total_characters", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lingarr_instance_id"],
            ["lingarr_instance.id"],
            name=op.f("fk_lingarr_actuals_lingarr_instance_id_lingarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lingarr_actuals")),
        sa.UniqueConstraint(
            "lingarr_instance_id", name="uq_lingarr_actuals_lingarr_instance_id"
        ),
    )
    with op.batch_alter_table("lingarr_actuals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lingarr_actuals_lingarr_instance_id"),
            ["lingarr_instance_id"],
            unique=False,
        )

    op.create_table(
        "doctor_finding",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "run_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("check_id", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column(
            "lingarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("fix_guidance", sa.Text(), nullable=False),
        sa.Column("data", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_doctor_finding_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lingarr_instance_id"],
            ["lingarr_instance.id"],
            name=op.f("fk_doctor_finding_lingarr_instance_id_lingarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["doctor_run.id"],
            name=op.f("fk_doctor_finding_run_id_doctor_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_finding")),
    )
    with op.batch_alter_table("doctor_finding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctor_finding_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index("ix_doctor_finding_check", ["check_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_doctor_finding_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "exclusion",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("rule_key", sa.String(length=128), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_exclusion_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exclusion")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "kind",
            "rule_key",
            name=op.f("uq_exclusion_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("exclusion", schema=None) as batch_op:
        batch_op.create_index(
            "ix_exclusion_instance_kind", ["bazarr_instance_id", "kind"], unique=False
        )

    op.create_table(
        "intent",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("media_type", sa.String(length=8), nullable=False),
        sa.Column("external_media_id", sa.Integer(), nullable=False),
        sa.Column("sonarr_series_id", sa.Integer(), nullable=True),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("display_title", sa.String(length=512), nullable=False),
        sa.Column("source_language", sa.String(length=8), nullable=False),
        sa.Column("target_language", sa.String(length=8), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hi", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("bumped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_trace", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_intent_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intent")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "media_type",
            "external_media_id",
            "target_language",
            "forced",
            "hi",
            name="uq_intent_identity",
        ),
    )
    with op.batch_alter_table("intent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_intent_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index("ix_intent_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_intent_instance_state", ["bazarr_instance_id", "state"], unique=False
        )
        batch_op.create_index(
            "ix_intent_series_pair",
            [
                "bazarr_instance_id",
                "sonarr_series_id",
                "source_language",
                "target_language",
            ],
            unique=False,
        )
        batch_op.create_index(
            "ix_intent_state_priority", ["state", "priority"], unique=False
        )

    op.create_table(
        "movie",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("radarr_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("sort_title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("audio_language", _json_column(), nullable=True),
        sa.Column("tags", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_movie_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movie")),
        sa.UniqueConstraint(
            "bazarr_instance_id", "radarr_id", name=op.f("uq_movie_bazarr_instance_id")
        ),
    )
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movie_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_movie_instance_sort_title",
            ["bazarr_instance_id", "sort_title"],
            unique=False,
        )

    op.create_table(
        "override",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("media_type", sa.String(length=8), nullable=False),
        sa.Column("media_key", sa.String(length=32), nullable=False),
        sa.Column("values", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_override_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_override")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "media_type",
            "media_key",
            name=op.f("uq_override_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("override", schema=None) as batch_op:
        batch_op.create_index(
            "ix_override_instance", ["bazarr_instance_id"], unique=False
        )

    op.create_table(
        "profile_assignment",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "profile_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("scope_key", sa.String(length=128), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_profile_assignment_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["translation_profile.id"],
            name=op.f("fk_profile_assignment_profile_id_translation_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_assignment")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "scope_type",
            "scope_key",
            name=op.f("uq_profile_assignment_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("profile_assignment", schema=None) as batch_op:
        batch_op.create_index(
            "ix_profile_assignment_instance", ["bazarr_instance_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_profile_assignment_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "rail_state",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=True,
        ),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column("dispatch_active", sa.Boolean(), nullable=False),
        sa.Column("window_k", sa.Integer(), nullable=True),
        sa.Column("breaker_state", sa.String(length=16), nullable=False),
        sa.Column("breaker_consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("breaker_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("breaker_last_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduling_windows", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_rail_state_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rail_state")),
        sa.UniqueConstraint(
            "bazarr_instance_id", name=op.f("uq_rail_state_bazarr_instance_id")
        ),
    )
    op.create_table(
        "series",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("sonarr_series_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("sort_title", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("ended", sa.Boolean(), nullable=True),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("audio_language", _json_column(), nullable=True),
        sa.Column("tags", _json_column(), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_series_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "sonarr_series_id",
            name=op.f("uq_series_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_series_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_series_instance_sort_title",
            ["bazarr_instance_id", "sort_title"],
            unique=False,
        )

    op.create_table(
        "stats_daily",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("media_type", sa.String(length=8), nullable=False),
        sa.Column("dispatched", sa.Integer(), nullable=False),
        sa.Column("converged", sa.Integer(), nullable=False),
        sa.Column("superseded", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("failed_transient", sa.Integer(), nullable=False),
        sa.Column("failed_environmental", sa.Integer(), nullable=False),
        sa.Column("failed_provider", sa.Integer(), nullable=False),
        sa.Column("failed_poison", sa.Integer(), nullable=False),
        sa.Column("converged_characters", sa.Integer(), nullable=False),
        sa.Column("duration_seconds_total", sa.Integer(), nullable=False),
        sa.Column("duration_samples", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_stats_daily_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stats_daily")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "day",
            "media_type",
            name="uq_stats_daily_instance_day_media",
        ),
    )
    with op.batch_alter_table("stats_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stats_daily_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index("ix_stats_daily_day", ["day"], unique=False)
        batch_op.create_index(
            "ix_stats_daily_instance_day", ["bazarr_instance_id", "day"], unique=False
        )

    op.create_table(
        "stats_language_daily",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("target_language", sa.String(length=8), nullable=False),
        sa.Column("converged", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_stats_language_daily_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stats_language_daily")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "day",
            "target_language",
            name="uq_stats_language_daily_instance_day_language",
        ),
    )
    with op.batch_alter_table("stats_language_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stats_language_daily_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_stats_language_daily_instance_day",
            ["bazarr_instance_id", "day"],
            unique=False,
        )

    op.create_table(
        "sync_run",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counters", _json_column(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_sync_run_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run")),
    )
    with op.batch_alter_table("sync_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_run_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_sync_run_instance_created",
            ["bazarr_instance_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "webhook_source",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=32), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_webhook_source_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_source")),
        sa.UniqueConstraint("name", name=op.f("uq_webhook_source_name")),
    )
    with op.batch_alter_table("webhook_source", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhook_source_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_webhook_source_token_hash"), ["token_hash"], unique=True
        )

    op.create_table(
        "episode",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column(
            "series_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("sonarr_series_id", sa.Integer(), nullable=False),
        sa.Column("sonarr_episode_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("audio_language", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_episode_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            name=op.f("fk_episode_series_id_series"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episode")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "sonarr_episode_id",
            name=op.f("uq_episode_bazarr_instance_id"),
        ),
    )
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_episode_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_episode_instance_series_number",
            ["bazarr_instance_id", "sonarr_series_id", "season", "episode"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_episode_series_id"), ["series_id"], unique=False
        )

    op.create_table(
        "intent_event",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "intent_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=16), nullable=True),
        sa.Column("to_state", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", _json_column(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["intent.id"],
            name=op.f("fk_intent_event_intent_id_intent"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intent_event")),
    )
    with op.batch_alter_table("intent_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_intent_event_intent_created", ["intent_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_intent_event_intent_id"), ["intent_id"], unique=False
        )

    op.create_table(
        "passthrough_action",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "intent_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("lingarr_request_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["intent.id"],
            name=op.f("fk_passthrough_action_intent_id_intent"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passthrough_action")),
    )
    with op.batch_alter_table("passthrough_action", schema=None) as batch_op:
        batch_op.create_index(
            "ix_passthrough_action_intent_created",
            ["intent_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_passthrough_action_intent_id"), ["intent_id"], unique=False
        )

    op.create_table(
        "subtitle",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column(
            "episode_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column(
            "movie_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hi", sa.Boolean(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_subtitle_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episode.id"],
            name=op.f("fk_subtitle_episode_id_episode"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
            name=op.f("fk_subtitle_movie_id_movie"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subtitle")),
    )
    with op.batch_alter_table("subtitle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subtitle_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_episode_id"), ["episode_id"], unique=False
        )
        batch_op.create_index(
            "ix_subtitle_instance_language",
            ["bazarr_instance_id", "language"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subtitle_movie_id"), ["movie_id"], unique=False
        )

    op.create_table(
        "wanted_subtitle",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "bazarr_instance_id",
            advanced_alchemy.types.guid.GUID(length=16),
            nullable=False,
        ),
        sa.Column(
            "episode_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column(
            "movie_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("hi", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bazarr_instance_id"],
            ["bazarr_instance.id"],
            name=op.f("fk_wanted_subtitle_bazarr_instance_id_bazarr_instance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episode.id"],
            name=op.f("fk_wanted_subtitle_episode_id_episode"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.id"],
            name=op.f("fk_wanted_subtitle_movie_id_movie"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wanted_subtitle")),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "episode_id",
            "language",
            "forced",
            "hi",
            name="uq_wanted_subtitle_bazarr_instance_id_episode_id",
        ),
        sa.UniqueConstraint(
            "bazarr_instance_id",
            "movie_id",
            "language",
            "forced",
            "hi",
            name="uq_wanted_subtitle_bazarr_instance_id_movie_id",
        ),
    )
    with op.batch_alter_table("wanted_subtitle", schema=None) as batch_op:
        batch_op.create_index(
            "ix_wanted_instance_language",
            ["bazarr_instance_id", "language"],
            unique=False,
        )
        batch_op.create_index(
            "ix_wanted_instance_last_seen",
            ["bazarr_instance_id", "last_seen_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_wanted_subtitle_bazarr_instance_id"),
            ["bazarr_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_wanted_subtitle_episode_id"), ["episode_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wanted_subtitle_movie_id"), ["movie_id"], unique=False
        )

    # ### end Alembic commands ###


def _seed_presets() -> None:
    preset = sa.table(
        "preset",
        sa.column("id", advanced_alchemy.types.guid.GUID(length=16)),
        sa.column("name", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("built_in", sa.Boolean()),
        sa.column("active", sa.Boolean()),
        sa.column("values", _json_column()),
        sa.column("rails", _json_column()),
        sa.column(
            "created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True)
        ),
        sa.column(
            "updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True)
        ),
    )
    now = datetime.now(UTC)
    op.bulk_insert(
        preset,
        [
            {
                "id": OBSERVE_ID,
                "name": "Observe",
                "description": (
                    "Dry-run only. Discovers, plans, and reports — dispatches "
                    "nothing. The default posture on install."
                ),
                "built_in": True,
                "active": True,
                "values": {"dry_run": True},
                "rails": {},
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": CONSERVATIVE_ID,
                "name": "Conservative",
                "description": (
                    "K=1, low daily cap, long grace periods, tight breaker — "
                    "for cautious starts and paid providers."
                ),
                "built_in": True,
                "active": False,
                "values": {
                    "dry_run": False,
                    "grace_hours_episodes": 336,
                    "grace_hours_movies": 720,
                },
                "rails": {
                    "dispatch_window_k": 1,
                    "daily_cap": 50,
                    "breaker_failure_threshold": 3,
                    "breaker_probe_minutes": 30,
                },
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": BALANCED_ID,
                "name": "Balanced",
                "description": (
                    "Moderate caps and window, budget ceiling on — sane "
                    "defaults for paid providers."
                ),
                "built_in": True,
                "active": False,
                "values": {
                    "dry_run": False,
                    "grace_hours_episodes": 168,
                    "grace_hours_movies": 336,
                },
                "rails": {
                    "dispatch_window_k": 2,
                    "daily_cap": 200,
                    "budget_daily_characters": 2_000_000,
                    "breaker_failure_threshold": 5,
                    "breaker_probe_minutes": 15,
                },
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": AGGRESSIVE_ID,
                "name": "Aggressive",
                "description": (
                    "Higher K and caps, short grace — for free/local providers."
                ),
                "built_in": True,
                "active": False,
                "values": {
                    "dry_run": False,
                    "grace_hours_episodes": 48,
                    "grace_hours_movies": 72,
                },
                "rails": {
                    "dispatch_window_k": 3,
                    "daily_cap": 1000,
                    "breaker_failure_threshold": 8,
                    "breaker_probe_minutes": 10,
                },
                "created_at": now,
                "updated_at": now,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wanted_subtitle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wanted_subtitle_movie_id"))
        batch_op.drop_index(batch_op.f("ix_wanted_subtitle_episode_id"))
        batch_op.drop_index(batch_op.f("ix_wanted_subtitle_bazarr_instance_id"))
        batch_op.drop_index("ix_wanted_instance_last_seen")
        batch_op.drop_index("ix_wanted_instance_language")

    op.drop_table("wanted_subtitle")
    with op.batch_alter_table("subtitle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtitle_movie_id"))
        batch_op.drop_index("ix_subtitle_instance_language")
        batch_op.drop_index(batch_op.f("ix_subtitle_episode_id"))
        batch_op.drop_index(batch_op.f("ix_subtitle_bazarr_instance_id"))

    op.drop_table("subtitle")
    with op.batch_alter_table("passthrough_action", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passthrough_action_intent_id"))
        batch_op.drop_index("ix_passthrough_action_intent_created")

    op.drop_table("passthrough_action")
    with op.batch_alter_table("intent_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intent_event_intent_id"))
        batch_op.drop_index("ix_intent_event_intent_created")

    op.drop_table("intent_event")
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episode_series_id"))
        batch_op.drop_index("ix_episode_instance_series_number")
        batch_op.drop_index(batch_op.f("ix_episode_bazarr_instance_id"))

    op.drop_table("episode")
    with op.batch_alter_table("webhook_source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_source_token_hash"))
        batch_op.drop_index(batch_op.f("ix_webhook_source_bazarr_instance_id"))

    op.drop_table("webhook_source")
    with op.batch_alter_table("sync_run", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_run_instance_created")
        batch_op.drop_index(batch_op.f("ix_sync_run_bazarr_instance_id"))

    op.drop_table("sync_run")
    with op.batch_alter_table("stats_language_daily", schema=None) as batch_op:
        batch_op.drop_index("ix_stats_language_daily_instance_day")
        batch_op.drop_index(batch_op.f("ix_stats_language_daily_bazarr_instance_id"))

    op.drop_table("stats_language_daily")
    with op.batch_alter_table("stats_daily", schema=None) as batch_op:
        batch_op.drop_index("ix_stats_daily_instance_day")
        batch_op.drop_index("ix_stats_daily_day")
        batch_op.drop_index(batch_op.f("ix_stats_daily_bazarr_instance_id"))

    op.drop_table("stats_daily")
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_index("ix_series_instance_sort_title")
        batch_op.drop_index(batch_op.f("ix_series_bazarr_instance_id"))

    op.drop_table("series")
    op.drop_table("rail_state")
    with op.batch_alter_table("profile_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_assignment_profile_id"))
        batch_op.drop_index("ix_profile_assignment_instance")

    op.drop_table("profile_assignment")
    with op.batch_alter_table("override", schema=None) as batch_op:
        batch_op.drop_index("ix_override_instance")

    op.drop_table("override")
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.drop_index("ix_movie_instance_sort_title")
        batch_op.drop_index(batch_op.f("ix_movie_bazarr_instance_id"))

    op.drop_table("movie")
    with op.batch_alter_table("intent", schema=None) as batch_op:
        batch_op.drop_index("ix_intent_state_priority")
        batch_op.drop_index("ix_intent_series_pair")
        batch_op.drop_index("ix_intent_instance_state")
        batch_op.drop_index("ix_intent_created_at")
        batch_op.drop_index(batch_op.f("ix_intent_bazarr_instance_id"))

    op.drop_table("intent")
    with op.batch_alter_table("exclusion", schema=None) as batch_op:
        batch_op.drop_index("ix_exclusion_instance_kind")

    op.drop_table("exclusion")
    with op.batch_alter_table("doctor_finding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctor_finding_run_id"))
        batch_op.drop_index("ix_doctor_finding_check")
        batch_op.drop_index(batch_op.f("ix_doctor_finding_bazarr_instance_id"))

    op.drop_table("doctor_finding")
    with op.batch_alter_table("lingarr_actuals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lingarr_actuals_lingarr_instance_id"))

    op.drop_table("lingarr_actuals")
    op.drop_table("bazarr_instance")
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_key_prefix"))

    op.drop_table("api_key")
    with op.batch_alter_table("watch_source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_source_source_type"))

    op.drop_table("watch_source")
    with op.batch_alter_table("watch_score", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_score_title_key"))
        batch_op.drop_index(batch_op.f("ix_watch_score_refreshed_at"))
        batch_op.drop_index(batch_op.f("ix_watch_score_media_type"))

    op.drop_table("watch_score")
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_account_username"))

    op.drop_table("user_account")
    op.drop_table("translation_profile")
    with op.batch_alter_table("preset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preset_active"))

    op.drop_table("preset")
    op.drop_table("notification_route")
    op.drop_table("lingarr_instance")
    op.drop_table("doctor_run")
    op.drop_table("auth_provider_config")
    op.drop_table("app_setup_state")
    # ### end Alembic commands ###
